//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Acteur = new HashSet<Acteur>();
        }
    
        public int FilmId { get; set; }
        public int IMDBNummer { get; set; }
        public string Naam { get; set; }
        public string AndereNaam { get; set; }
        public string Versie { get; set; }
        public int AantalDisks { get; set; }
        public System.DateTime Jaar { get; set; }
        public string Land { get; set; }
        public int Speelduur { get; set; }
        public string Kijkwijzer { get; set; }
        public bool Gezien { get; set; }
        public bool Wenslijst { get; set; }
        public bool InBezit { get; set; }
        public bool Kleur { get; set; }
        public bool ZW { get; set; }
        public bool KleurZW { get; set; }
        public System.DateTime ToegevoegdDate { get; set; }
        public bool Serie { get; set; }
        public bool DrieD { get; set; }
        public string Verhaal { get; set; }
        public int IMDBRate { get; set; }
        public int PersRate { get; set; }
        public string Afbeelding { get; set; }
        public string Taalnaam { get; set; }
        public string GenreNaam { get; set; }
        public int RegisseurRegID { get; set; }
    
        public virtual Regisseur Regisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acteur> Acteur { get; set; }
    }
}
